template: Hello, %s!

defaultName: Stranger

database:
  driverClass: com.mysql.jdbc.Driver
  user: bradybunch
  password: bradybunch
  url: jdbc:mysql://localhost/bradybunch
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect

server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: example.keystore
      keyStorePassword: example
      validateCerts: false
# this requires the npn-boot library on the JVM's boot classpath
#    - type: spdy3
#      port: 8445
#      keyStorePath: example.keystore
#      keyStorePassword: example
#      validateCerts: false
  adminConnectors:
    - type: http
      port: 8081
    - type: https
      port: 8444
      keyStorePath: example.keystore
      keyStorePassword: example
      validateCerts: false

logging:
  level: INFO
  loggers:
    com.example.app: DEBUG
    org.hibernate.SQL: ALL
  appenders:
    - type: console
