database:
  driverClass: org.postgresql.Driver
  user: <heroku_db_user>
  password: <heroku_db_password>
  url: jdbc:postgresql://<heroku_db_host>/<heroku_db_path>
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

logging:
  level: INFO
  loggers:
    com.palominolabs: INFO
    org.hibernate.SQL: ALL
    org.atmosphere: INFO
  appenders:
    - type: console
