template: Hello, %s!

defaultName: Stranger

database:
  driverClass: com.mysql.jdbc.Driver
  user: bradybunch
  password: bradybunch
  url: jdbc:mysql://localhost/bradybunch
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect

http:
  port: 8080
  adminPort: 8081
  maxThreads: 100
  minThreads: 10
  connectorType: nonblocking
  maxIdleTime: 1s
  acceptorThreads: 3
  acceptorThreadPriorityOffset: 0
  acceptQueueSize: 100
  maxBufferCount: 1024
  requestBufferSize: 32KB
  requestHeaderBufferSize: 6KB
  responseBufferSize: 32KB
  responseHeaderBufferSize: 6KB
  reuseAddress: true
  soLingerTime: 1s
  lowResourcesConnectionThreshold: 25000
  lowResourcesMaxIdleTime: 5s
  shutdownGracePeriod: 2s
  useForwardedHeaders: true
  useDirectBuffers: true
#  ssl:
#    keyStore: ./example.keystore
#    keyStorePassword: example
#    keyStoreType: JKS # (optional, JKS is default)
  requestLog:
    console:
      enabled: true
    file:
      enabled: true
      currentLogFilename: ./logs/requests.log
      archivedLogFilenamePattern: ./logs/requests-%d.log.gz
      archivedFileCount: 5
    syslog:
      enabled: false
      host: localhost
      facility: local0

logging:
  level: DEBUG
  loggers:
    com.palominolabs.helloWorld: DEBUG
    org.hibernate.SQL: ALL
  console:
    enabled: true
    threshold: ALL
  file:
    enabled: true
    threshold: ALL
    currentLogFilename: ./logs/example.log
    archivedLogFilenamePattern: ./logs/example-%d.log.gz
    archivedFileCount: 5
  syslog:
    enabled: false
    host: localhost
    facility: local0
